repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.7
  hooks:
    # Run the linter of backend.
    - id: ruff
    # Run the formatter of backend.
    - id: ruff-format
    # Run the linter of frontend.
    - id: eslint
    # Run the formatter of frontend.
    - id: eslint-format
